// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Error": {
    "description": "<p>We've unfortunately encountered an error.</p><p>You can try to <retry>reload the page</retry> you were visiting.</p>",
    "title": "Something went wrong!"
  },
  "IndexPage": {
    "description": "This is a basic example that demonstrates the usage of <code>next-intl</code> with the Next.js App Router. Try changing the locale in the top right corner and see how the content changes.",
    "title": "content"
  },
  "LocaleLayout": {
    "title": "fuad sayt basliqi"
  },
  "LocaleSwitcher": {
    "label": "Change language",
    "locale": "{locale, select, az {🇦🇿 Az} en {🇺🇸 Eng} other {Unknown}}"
  },
  "Manifest": {
    "name": "next-intl example"
  },
  "Navigation": {
    "home": "Ana səhifə",
    "tours": "Turlar",
    "excursions": "Ekskursiyalar",
    "visa_services": "Viza dəstəyi",
    "about": "Haqqımızda",
    "blogs": "Bloqlar",
    "contact": "Əlaqə",
    "countries": "Ölkələr"
  },
  "PageTitles": {
    "home": "Ana səhifə",
    "tours": "Turlar",
    "excursions": "Ekskursiyalar",
    "visa_services": "Viza dəstəyi",
    "about": "Haqqımızda",
    "blogs": "Bloglar",
    "contact": "Əlaqə",
    "countries": "Ölkələr"
  },
  "NotFoundPage": {
    "description": "Please double-check the browser address bar or use the navigation to go to a known page.",
    "title": "Page not found"
  },
  "PageLayout": {
    "links": {
      "docs": {
        "description": "Learn more about next-intl in the official docs.",
        "href": "https://next-intl.dev",
        "title": "Docs"
      },
      "source": {
        "description": "Browse the source code of this example on GitHub.",
        "href": "https://github.com/amannn/next-intl/tree/main/examples/example-app-router",
        "title": "Source code"
      }
    }
  },
  "PathnamesPage": {
    "description": "<p>The pathnames are internationalized too.</p><p>If you're using the default language English, you'll see <code>/en/pathnames</code> in the browser address bar on this page.</p><p>If you change the locale to German, the URL is localized accordingly (<code>/de/pfadnamen</code>).</p>",
    "title": "Pathnames"
  },
  "FiltersPlaceholders": {
    "categories": "Kateqoriyalar",
    "countries": "Ölkələr",
    "cities": "Şəhərlər",
    "filter": "Sıralama",
    "excursionsType": "Ekskursiya növləri",
    "citizenshipCountry": "Vətəndaşı olduğunuz ölkə",
    "residenceCountry": "Yaşadığınız ölkə",
    "travelCountry": "Səyahət ölkəsi"
  },
  "ButtonsValue": {
    "apply": "Müraciət et"
  },
  "FAQ":"Ən çox verilən suallar"
};
export default messages;